# Generated by Django 5.2.4 on 2025-08-31 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyname', models.CharField(max_length=32)),
                ('sshkey', models.CharField(max_length=256)),
                ('fingerprint', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssh_key',
                'unique_together': {('user', 'keyname')},
            },
        ),
    ]
