#https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete
networks:
  cloudgit:

services:
  # docker build -t cloudgit-auth --build-context common=./backend/common  backend/services/auth
  auth:
    restart: always
    image: cloudgit-auth:latest
    container_name: auth
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: "1001:1001"
    networks:
      - cloudgit
    ports:
      - 127.0.0.1:8000:${AUTH_PORT}
    env_file:
      - ./.env
    environment:
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_RABBITMQ_HOST: 'rabbitmq'
      DJANGO_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
      DJANGO_RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DJANGO_RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      DJANGO_RABBITMQ_VHOST: '/'
      DJANGO_POSTGRES_DB_NAME: ${AUTH_DB_NAME}
      DJANGO_POSTGRES_HOST: 'auth_db'
      DJANGO_POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
      DJANGO_POSTGRES_USER: ${CLOUDGIT_USER}
      DJANGO_SECRET_KEY: ${AUTH_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: settings
      GUNICORN_HOST: ${AUTH_HOST}
      GUNICORN_PORT: ${AUTH_PORT}
      REMOTE_SERVER_URL: ${SCHEME}://${NGINX_EXT_HOST}:${NGINX_EXT_PORT}
    command: >
      sh -c "
      python ./manage.py migrate &&
      python ./run.py"
    depends_on:
      auth_db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_started
        restart: true

  auth_db:
    restart: always
    build:
      context: ./backend/services/auth/db
      args:
        PGDATA: ${PGDATA}
        POSTGRES_DB: ${AUTH_DB_NAME}
        POSTGRES_USER: ${CLOUDGIT_USER}
        POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: auth_db
    networks:
      - cloudgit
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${AUTH_DB_NAME} -U $${CLOUDGIT_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 127.0.0.1:5430:${POSTGRES_PORT}
    volumes:
      - auth_db_data:${PGDATA}

  # docker build -t cloudgit-repo --build-context common=./backend/common  backend/services/repo
  repo:
    restart: always
    image: cloudgit-repo:latest
    container_name: repo
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: "1001:1001"
    networks:
      - cloudgit
    ports:
      - 127.0.0.1:8001:${REPO_PORT}
    env_file:
      - ./.env
    environment:
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_RABBITMQ_HOST: 'rabbitmq'
      DJANGO_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
      DJANGO_RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DJANGO_RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      DJANGO_RABBITMQ_VHOST: '/'
      DJANGO_POSTGRES_DB_NAME: ${REPO_DB_NAME}
      DJANGO_POSTGRES_HOST: 'repo_db'
      DJANGO_POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
      DJANGO_POSTGRES_USER: ${CLOUDGIT_USER}
      DJANGO_SECRET_KEY: ${REPO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: settings
      GUNICORN_HOST: ${REPO_HOST}
      GUNICORN_PORT: ${REPO_PORT}
      REMOTE_SERVER_URL: ${SCHEME}://${NGINX_EXT_HOST}:${NGINX_EXT_PORT}
      STORAGE_1_CLIENT_KEY_PATH: ~/.ssh/${STORAGE_1_NAME}
      STORAGE_1_USERNAME: ${CLOUDGIT_USER}
      STORAGE_2_CLIENT_KEY_PATH: ~/.ssh/${STORAGE_2_NAME}
      STORAGE_2_USERNAME: ${CLOUDGIT_USER}
    command: >
      sh -c "
      python ./manage.py migrate &&
      python ./run.py"
    depends_on:
      repo_db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_started
        restart: true

  repo_db:
    restart: always
    build:
      context: ./backend/services/repo/db
      args:
        PGDATA: ${PGDATA}
        POSTGRES_DB: ${REPO_DB_NAME}
        POSTGRES_USER: ${CLOUDGIT_USER}
        POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: repo_db
    networks:
      - cloudgit
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${REPO_DB_NAME} -U $${CLOUDGIT_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 127.0.0.1:5429:${POSTGRES_PORT}
    volumes:
      - repo_db_data:${PGDATA}
  
  pgadmin:
    restart: always
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    networks:
      - cloudgit
    env_file:
      - ./.env
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - 127.0.0.1:5080:80
    depends_on:
      auth_db:
        condition: service_healthy
        restart: true

  frontend:
    restart: always
    build:
      context: ./frontend
      args:
        VITE_DEBUG: ${DEBUG}
        VITE_REMOTE_SERVER_URL: ${SCHEME}://${NGINX_EXT_HOST}
    env_file:
      - ./.env
    container_name: frontend
    ports:
      - 127.0.0.1:3000:${FRONTEND_PORT}
    networks:
      - cloudgit

  rabbitmq:
    restart: always
    image: rabbitmq:4.1.2-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
      - ./.env
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 536870912
    ports:
      - 127.0.0.1:5672:${RABBITMQ_NODE_PORT} # AMQP
      - 127.0.0.1:15672:15672                # management
    networks:
      - cloudgit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  storage_1:
    restart: always
    build:
      context: ./storages/
      args:
        STORAGE_PATH: ${STORAGE_1_PATH}
        USERNAME: ${CLOUDGIT_USER}
        PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: storage_1
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:2222:22"
    command: >
      sh -c "
      cat ~/.ssh/${STORAGE_1_NAME}.pub >> ~/.ssh/authorized_keys &&
      sudo /usr/sbin/sshd -D"
    volumes:
      - storage_1_data:${STORAGE_1_PATH}
      - ~/.ssh/${STORAGE_1_NAME}.pub:/home/${CLOUDGIT_USER}/.ssh/${STORAGE_1_NAME}.pub

  storage_2:
    restart: always
    build:
      context: ./storages/
      args:
        STORAGE_PATH: ${STORAGE_2_PATH}
        USERNAME: ${CLOUDGIT_USER}
        PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: storage_2
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:2223:22"
    command: >
      sh -c "
      cat ~/.ssh/${STORAGE_2_NAME}.pub > ~/.ssh/authorized_keys &&
      sudo /usr/sbin/sshd -D"
    volumes:
      - storage_2_data:${STORAGE_2_PATH}
      - ~/.ssh/${STORAGE_2_NAME}.pub:/home/${CLOUDGIT_USER}/.ssh/${STORAGE_2_NAME}.pub

  nginx:
    restart: always
    build:
      context: ./nginx
      args:
        AUTH_PORT: ${AUTH_PORT}
        FRONTEND_PORT: ${FRONTEND_PORT}
        RABBITMQ_NODE_PORT: ${RABBITMQ_NODE_PORT}
        REPO_PORT: ${REPO_PORT}
    container_name: nginx
    user: "1001:1001"
    env_file:
      - ./.env
    ports:
      - ${NGINX_EXT_HOST}:${NGINX_EXT_PORT}:80
    networks:
      - cloudgit
    depends_on:
      - rabbitmq
      - frontend
      - auth
      - repo

  nginx-dev:
    image: nginx:1.29.0-alpine-slim
    container_name: nginx-dev
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:23:22"
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rabbitmq
      - auth_db
      - repo_db
      - storage_1
      - storage_2

volumes:
  auth_db_data:
  repo_db_data:
  rabbitmq_data:
  storage_1_data:
  storage_2_data:
