enum REPOACCESS {
	public
	private
}



enum MAINTAINERACCESS {
	full
	partial
}

Table storage {
	id bigserial [ pk, not null, unique ]
	link varchar(255) [ not null ]
}

Table file {
	id bigserial [ pk, not null, unique ]
	name varchar(255) [ not null ]
	path varchar(255) [ not null, note: 'relative path into repo' ]
	ext varchar(255) [ note: '`NULL` equal without extension' ]
	branch_id bigint [ not null ]

	indexes {
		(branch_id) [ name: 'file_index_branch_id' ]
		(ext) [ name: 'file_index_ext' ]
	}
}

Table repo {
	id bigserial [ pk, not null, unique ]
	user_id integer [ not null, note: 'repo holder' ]
	storage_id bigint [ note: '`NULL` when repo store locale' ]
	name char(32) [ not null ]
	access repoaccess [ not null, note: 'values: private, public' ]
	path varchar(255) [ not null, note: 'path into storage' ]

	indexes {
		(user_id) [ name: 'repo_index_user_id' ]
		(storage_id) [ name: 'repo_index_storage_id' ]
		(access) [ name: 'repo_index_access' ]
	}
}

Table maintainer {
	id bigserial [ pk, not null, unique ]
	repo_id bigint [ not null ]
	user_id integer [ not null ]
	access maintaineraccess [ not null, note: 'values: full, partial' ]

	indexes {
		(repo_id) [ name: 'maintainer_index_repo_id' ]
	}
}

Table branch {
	id bigserial [ pk, not null, unique ]
	repo_id bigint [ not null ]
	name varchar(255) [ not null ]
	is_default boolean [ not null ]

	indexes {
		(repo_id) [ name: 'branch_index_repo_id' ]
		(default) [ name: 'branch_index_is_default' ]
	}
}

Table auth_user_external {
	id serial [ pk, not null, unique ]
	user_id integer [ not null ]
}

Ref fk_repo_storage_id_storage {
	repo.storage_id > storage.id [ delete: set null, update: cascade ]
}

Ref fk_maintainer_repo_id_repo {
	maintainer.repo_id > repo.id [ delete: cascade, update: cascade ]
}

Ref fk_branch_repo_id_repo {
	branch.repo_id > repo.id [ delete: cascade, update: cascade ]
}

Ref fk_file_branch_id_branch {
	file.branch_id > branch.id [ delete: cascade, update: cascade ]
}

Ref fk_repo_user_id_auth_user_external {
	repo.user_id > auth_user_external.id [ delete: cascade, update: cascade ]
}

Ref fk_maintainer_user_id_auth_user_external {
	maintainer.user_id > auth_user_external.id [ delete: cascade, update: cascade ]
}