# Generated by Django 5.2.4 on 2025-07-05 21:16

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserExternal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_external',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(db_comment='relative path into repo', max_length=255)),
                ('ext', models.CharField(blank=True, db_comment='`NULL` equal without extension', max_length=255, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repo.branch')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('access', django_enum.fields.EnumCharField(choices=[('PR', 'private'), ('PU', 'public')], db_comment='values: private, public', max_length=2)),
                ('path', models.CharField(db_comment='path into storage', max_length=255)),
                ('user', models.ForeignKey(db_comment='repo holder', on_delete=django.db.models.deletion.DO_NOTHING, to='repo.authuserexternal')),
                ('storage', models.ForeignKey(blank=True, db_comment='`NULL` when repo store locale', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repo.storage')),
            ],
            options={
                'db_table': 'repo',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repo.repo'),
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access', django_enum.fields.EnumCharField(choices=[('f', 'full'), ('p', 'partial')], db_comment='values: full, partial', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repo.authuserexternal')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repo.repo')),
            ],
            options={
                'db_table': 'maintainer',
                'constraints': [models.CheckConstraint(condition=models.Q(('access__in', ['f', 'p'])), name='repo_Maintainer_access_AccessEnum')],
            },
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.CheckConstraint(condition=models.Q(('access__in', ['PR', 'PU'])), name='repo_Repo_access_AccessEnum'),
        ),
    ]
