# Generated by Django 5.2.4 on 2025-07-05 22:09

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.repo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.branch'),
        ),
        migrations.AlterField(
            model_name='file',
            name='ext',
            field=models.CharField(blank=True, db_comment='`NULL` equal without extension', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.repo'),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='repo.authuserexternal'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='access',
            field=django_enum.fields.EnumCharField(choices=[('PR', 'private'), ('PU', 'public')], db_comment='values: private, public', db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='repo',
            name='storage',
            field=models.ForeignKey(blank=True, db_comment='`NULL` when repo store locale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.storage'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='user',
            field=models.ForeignKey(db_comment='repo holder', on_delete=django.db.models.deletion.CASCADE, to='repo.authuserexternal'),
        ),
    ]
