# Generated by Django 5.2.4 on 2025-07-30 00:40

import apps.repo.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_branch_is_default_alter_branch_repo_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuserexternal',
            managers=[
                ('objects', apps.repo.managers.AuthUserExternalManager()),
            ],
        ),
        migrations.AddField(
            model_name='authuserexternal',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authuserexternal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='authuserexternal',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='user id'),
        ),
    ]
