# Generated by Django 5.2.4 on 2025-07-30 02:08

import apps.repo.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_authuserexternal_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='storage',
            managers=[
                ('objects', apps.repo.managers.StorageManager()),
            ],
        ),
    ]
