# Generated by Django 5.2.4 on 2025-08-03 22:03

import apps.repo.managers
import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_storage_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='repo',
            managers=[
                ('objects', apps.repo.managers.RepoManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='repo',
            name='name',
        ),
        migrations.AddField(
            model_name='repo',
            name='description',
            field=models.CharField(default='', max_length=50, verbose_name='repo description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='repo_name',
            field=models.CharField(default='', error_messages={'max_length': 'Repo name must be less than 32 characters.'}, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(default='', error_messages={'max_length': 'Storage name must be less than 32 characters.'}, help_text='Required. May be unique.', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='path',
            field=models.CharField(default='', error_messages={'max_length': 'Path must be less than 255 characters.'}, help_text='Required. Path into storage server.', max_length=255, verbose_name='storage path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('LO', 'local'), ('RE', 'remote')], db_comment='values: local, remote', default='', help_text="Required. Type of repo may be 'local' or 'remote'.'", max_length=2, verbose_name='storage type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo',
            name='storage',
            field=models.ForeignKey(db_comment='local or remote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.storage'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='link',
            field=models.CharField(error_messages={'max_length': 'Storage link must be less than 255 characters.'}, help_text='Required. Link to remote storage. If storage is local, then set null.', max_length=255, null=True, verbose_name='storage link'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['LO', 'RE'])), name='repo_Storage_type_TypeEnum'),
        ),
    ]
