# Generated by Django 5.2.4 on 2025-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_alter_repo_managers_remove_repo_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintainer',
            name='repo_Maintainer_access_AccessEnum',
        ),
        migrations.RemoveConstraint(
            model_name='repo',
            name='repo_Repo_access_AccessEnum',
        ),
        migrations.RemoveConstraint(
            model_name='storage',
            name='repo_Storage_type_TypeEnum',
        ),
        migrations.AddConstraint(
            model_name='maintainer',
            constraint=models.CheckConstraint(condition=models.Q(('access__in', ['f', 'p'])), name='repo_Maintainer_access_MaitainerAccessEnum'),
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.CheckConstraint(condition=models.Q(('access__in', ['PR', 'PU'])), name='repo_Repo_access_RepoAccessEnum'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['LO', 'RE'])), name='repo_Storage_type_StorageTypeEnum'),
        ),
    ]
