# Generated by Django 5.2.4 on 2025-08-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_remove_maintainer_repo_maintainer_access_accessenum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('user', 'repo_name')},
        ),
    ]
