# Generated by Django 5.2.4 on 2025-08-09 23:01

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_alter_repo_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storage',
            name='repo_Storage_type_StorageTypeEnum',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='path',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='link',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='type',
        ),
        migrations.AddField(
            model_name='storage',
            name='general_size',
            field=models.PositiveIntegerField(default=500, verbose_name='Storage size in MB.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='used_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Storage used size in MB.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='ssh_host',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='ssh_password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='ssh_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='ssh_username',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='storage',
            name='available_size',
            field=models.GeneratedField(db_comment='If < 500mb, then storage will not be available for creating new repositories.', db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('general_size'), '-', models.F('used_size')), output_field=models.PositiveIntegerField()),
        ),
    ]
