# Generated by Django 5.2.4 on 2025-08-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_remove_storage_repo_storage_type_storagetypeenum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='ssh_password',
        ),
        migrations.AddField(
            model_name='repo',
            name='path',
            field=models.CharField(default='', max_length=255, verbose_name='repo path into storage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='general_size',
            field=models.PositiveIntegerField(verbose_name='Storage size in KB.'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='used_size',
            field=models.PositiveIntegerField(verbose_name='Storage used size in KB.'),
        ),
    ]
