# Generated by Django 5.2.4 on 2025-08-18 03:19

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_remove_storage_ssh_password_repo_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='available_size',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='general_size',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='used_size',
        ),
        migrations.AddField(
            model_name='repo',
            name='general_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Repo size in KB.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='used_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Repo used size in KB.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo',
            name='path',
            field=models.CharField(max_length=255, verbose_name='repo absolute path into storage'),
        ),
        migrations.AddField(
            model_name='repo',
            name='available_size',
            field=models.GeneratedField(db_comment='If < 500mb, then storage will not be available for creating new repositories.', db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('general_size'), '-', models.F('used_size')), output_field=models.PositiveIntegerField()),
        ),
    ]
