# Generated by Django 5.2.4 on 2025-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0010_remove_storage_available_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserexternal',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
