#https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete
networks:
  cloudgit:

services:
  auth:
    restart: always
    build:
      context: ../backend/services/auth
      additional_contexts:
        - common=../backend/common
      args:
        USERNAME: ${CLOUDGIT_USER}
    container_name: auth
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    environment:
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_RABBITMQ_HOST: 'rabbitmq'
      DJANGO_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
      DJANGO_RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DJANGO_RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      DJANGO_RABBITMQ_VHOST: '/'
      DJANGO_POSTGRES_DB_NAME: ${AUTH_DB_NAME}
      DJANGO_POSTGRES_HOST: 'auth_db'
      DJANGO_POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
      DJANGO_POSTGRES_USER: ${CLOUDGIT_USER}
      DJANGO_SECRET_KEY: ${AUTH_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: settings
      GUNICORN_HOST: ${AUTH_HOST}
      GUNICORN_PORT: ${AUTH_PORT}
    command: >
      sh -c "
      python ./manage.py migrate &&
      python ./run.py"
    depends_on:
      auth_db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_started
        restart: true

  auth_db:
    restart: always
    build:
      context: ../backend/services/auth/db
      args:
        PGDATA: ${PGDATA}
        POSTGRES_DB: ${AUTH_DB_NAME}
        POSTGRES_USER: ${CLOUDGIT_USER}
        POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: auth_db
    networks:
      - cloudgit
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${AUTH_DB_NAME} -U $${CLOUDGIT_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - auth_db_data:${PGDATA}

  repo:
    restart: always
    build:
      context: ../backend/services/repo
      additional_contexts:
        - common=../backend/common
      args:
        USERNAME: ${CLOUDGIT_USER}
    container_name: repo
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    environment:
      DJANGO_DEBUG: ${DEBUG}
      DJANGO_RABBITMQ_HOST: 'rabbitmq'
      DJANGO_RABBITMQ_PORT: ${RABBITMQ_NODE_PORT}
      DJANGO_RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DJANGO_RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      DJANGO_RABBITMQ_VHOST: '/'
      DJANGO_POSTGRES_DB_NAME: ${REPO_DB_NAME}
      DJANGO_POSTGRES_HOST: 'repo_db'
      DJANGO_POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
      DJANGO_POSTGRES_USER: ${CLOUDGIT_USER}
      DJANGO_SECRET_KEY: ${REPO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: settings
      GUNICORN_HOST: ${REPO_HOST}
      GUNICORN_PORT: ${REPO_PORT}
      STORAGE_1_CLIENT_KEY_PATH: ${CLIENT_KEYS_DIR}/${STORAGE_1_NAME}
      STORAGE_1_USERNAME: ${CLOUDGIT_USER}
      STORAGE_2_CLIENT_KEY_PATH: ${CLIENT_KEYS_DIR}/${STORAGE_2_NAME}
      STORAGE_2_USERNAME: ${CLOUDGIT_USER}
    command: >
      sh -c "
      python ./manage.py migrate &&
      python ./run.py"
    depends_on:
      repo_db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_started
        restart: true
    volumes:
      - ../_ssh/storage_keys/:${CLIENT_KEYS_DIR}

  repo_db:
    restart: always
    build:
      context: ../backend/services/repo/db
      args:
        PGDATA: ${PGDATA}
        POSTGRES_DB: ${REPO_DB_NAME}
        POSTGRES_USER: ${CLOUDGIT_USER}
        POSTGRES_PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: repo_db
    networks:
      - cloudgit
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${REPO_DB_NAME} -U $${CLOUDGIT_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - repo_db_data:${PGDATA}
  
  pgadmin:
    restart: always
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    networks:
      - cloudgit
    env_file:
      - ./.env
    environment:
      PGUSER: ${CLOUDGIT_USER}

  sshproxy:
    restart: always
    build:
      context: ../backend/services/sshproxy
      additional_contexts:
        - common=../backend/common
      args:
        USERNAME: ${CLOUDGIT_USER}
    container_name: sshproxy
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    environment:
      SSHPROXY_AUTHORIZED_KEYS: /home/${CLOUDGIT_USER}/.ssh/authorized_keys
      SSHPROXY_CLIENT_KEYS: ${CLIENT_KEYS_DIR}/${STORAGE_1_NAME};${CLIENT_KEYS_DIR}/${STORAGE_2_NAME};
      SSHPROXY_SERVER_HOST_KEYS: ${HOST_KEYS_DIR}/ssh_host_ed25519_key;${HOST_KEYS_DIR}/ssh_host_rsa_key;${HOST_KEYS_DIR}/ssh_host_ecdsa_key;
    command: >
      sh -c "
      python server/run.py"
    volumes:
      - ssh_proxy_auth_keys:/home/${CLOUDGIT_USER}/.ssh/authorized_keys
      - ../_ssh/sshproxy_host_keys/:${HOST_KEYS_DIR}/
      - ../_ssh/storage_keys/:${CLIENT_KEYS_DIR}/

  frontend:
    restart: always
    build:
      context: ../frontend
      args:
        VITE_DEBUG: ${DEBUG}
        VITE_REMOTE_SERVER_URL: ${SCHEME}://${NGINX_EXT_HOST}:${NGINX_HTTP_EXT_PORT}
    env_file:
      - ./.env
    container_name: frontend
    networks:
      - cloudgit

  rabbitmq:
    restart: always
    image: rabbitmq:4.1.2-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
      - ./.env
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 536870912
    networks:
      - cloudgit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  storage_1:
    restart: always
    build:
      context: ../storages/
      args:
        STORAGE_PATH: ${STORAGE_1_PATH}
        USERNAME: ${CLOUDGIT_USER}
        PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: storage_1
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    command: >
      sh -c "
      cat ~/.ssh/${STORAGE_1_NAME}.pub >> ~/.ssh/authorized_keys &&
      sudo /usr/sbin/sshd -D"
    volumes:
      - storage_1_data:${STORAGE_1_PATH}
      - ../_ssh/storage_keys/${STORAGE_1_NAME}.pub:/home/${CLOUDGIT_USER}/.ssh/${STORAGE_1_NAME}.pub

  storage_2:
    restart: always
    build:
      context: ../storages/
      args:
        STORAGE_PATH: ${STORAGE_2_PATH}
        USERNAME: ${CLOUDGIT_USER}
        PASSWORD: ${CLOUDGIT_PASSWORD}
    container_name: storage_2
    user: "1001:1001"
    networks:
      - cloudgit
    env_file:
      - ./.env
    command: >
      sh -c "
      cat ~/.ssh/${STORAGE_2_NAME}.pub > ~/.ssh/authorized_keys &&
      sudo /usr/sbin/sshd -D"
    volumes:
      - storage_2_data:${STORAGE_2_PATH}
      - ../_ssh/storage_keys/${STORAGE_2_NAME}.pub:/home/${CLOUDGIT_USER}/.ssh/${STORAGE_2_NAME}.pub

volumes:
  auth_db_data:
  repo_db_data:
  rabbitmq_data:
  ssh_proxy_auth_keys:
  storage_1_data:
  storage_2_data:
