worker_processes auto;

events {
    worker_connections 1024;
}

http {
   upstream auth {
      least_conn;
      server auth:$AUTH_PORT max_fails=5 fail_timeout=60s;
   }
   server {
      listen 80;
      
      server_name localhost;

      location / {
          include proxy_params;
          proxy_pass http://frontend:$FRONTEND_PORT/;
          proxy_redirect off;
          proxy_http_version 1.1;
      }
      
      location /api/auth/ {
          include proxy_params;
          proxy_pass http://auth/api/auth/;
          proxy_redirect off;
          proxy_http_version 1.1;
      }

      location /rabbitmq/ {
          include proxy_params;
          proxy_pass http://rabbitmq:$RABBITMQ_NODE_PORT/;
          proxy_redirect off;
          proxy_http_version 1.1;
      }
   }
}
