CREATE DATABASE $POSTGRES_DB;

CREATE ROLE $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';

ALTER ROLE "$POSTGRES_USER" WITH LOGIN;

GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO $POSTGRES_USER;

ALTER USER $POSTGRES_USER CREATEDB;

\c $POSTGRES_DB

GRANT ALL ON SCHEMA public TO $POSTGRES_USER;
